Update "Email" in Model to "Cycle"
AY2324S1-CS2103T-W17-2/tp pull request #46
Opened 2023-10-07 20:03 UTC by zsh-eng

- Rename Email to Cycle
- Fix broken tests
- Update Cycle to allow for hyphens

Fixes #37

2023-10-07 20:19 UTC, tim-pipi requested changes
Overall, LGTM! Just some nits to pick about sample data and unnecessary changes!

2023-10-07 20:19 UTC, tim-pipi commented on docs/AboutUs.md
> +You can reach us at the cycle `seer[at]comp.nus.edu.sg`
Perhaps this change should be reverted? 
```suggestion
You can reach us at the email `seer[at]comp.nus.edu.sg`
```

2023-10-07 20:19 UTC, tim-pipi commented on docs/tutorials/RemovingFields.md
I am unsure whether changes to the tutorials are needed. Will check with the rest tomorrow!

2023-10-07 20:19 UTC, tim-pipi commented on src/main/java/seedu/address/logic/commands/AddCommand.java
> +            + PREFIX_CYCLE + "johnd@example.com "
Perhaps you could change the sample data as well? Something like the following
```suggestion
            + PREFIX_CYCLE + "Summer "
```

I saw this in some other parts of the code as well!

2023-10-07 20:19 UTC, tim-pipi commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +            + PREFIX_CYCLE + "johndoe@example.com";
Perhaps something like this would be better?

```suggestion
            + PREFIX_CYCLE + "Summer";
```

2023-10-07 20:19 UTC, tim-pipi commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
> +            new InternApplication(new Name("Alex Yeoh"), new Phone("87438807"), new Cycle("alexyeoh@example.com"),
```suggestion
            new InternApplication(new Name("Alex Yeoh"), new Phone("87438807"), new Cycle("Summer"),
```

2023-10-07 20:19 UTC, tim-pipi commented on src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
> +    "cycle": "Summer 2024",
Nice! Perhaps sample data like this one could be implemented in the other parts that you've changed as well!

2023-10-10 14:25 UTC, zsh-eng commented on docs/AboutUs.md
> +You can reach us at the cycle `seer[at]comp.nus.edu.sg`
Noted thanks!

2023-10-10 16:14 UTC, merged