Add Note Command
AY2324S1-CS2103T-W17-2/tp pull request #57
Opened 2023-10-16 16:12 UTC by AprupKale

Fixes #2 

Add the note command, and update the logic and model accordingly

2023-10-16 16:13 UTC, AprupKale commented
Yet to integrate with Storage and finalize the other classes

Not ready to merge!

2023-10-16 16:42 UTC, tim-pipi requested changes
Hey Aprup, I think there are some part of the changes that you made that could be made more standardized - following how the rest of the commands were implemented! 

Thanks for doing this!

2023-10-16 16:42 UTC, tim-pipi commented on docs/UserGuide.md
> +* `note 1 i/John Street is the leading market maker in the APAC region` adds the note 'John Street is the leading market maker in the APAC regio' to first internship application entry (in the list)
```suggestion
* `note 1 i/John Street is the leading market maker in the APAC region` adds the note 'John Street is the leading market maker in the APAC region' to the first internship application entry (in the list)
```

Typo here!

2023-10-16 16:42 UTC, tim-pipi commented on docs/UserGuide.md
> +| **Note**   | `note INDEX`<br> e.g., `note 5 i/John Street is the leading market maker in the APAC region`
I think these lines are missing the right `|`

2023-10-16 16:42 UTC, tim-pipi commented on src/main/java/seedu/letsgethired/logic/parser/AddCommandParser.java
> +import seedu.letsgethired.model.application.*;
Should these remain specified individually (checkstyle error)?

2023-10-16 16:42 UTC, tim-pipi commented on src/main/java/seedu/letsgethired/logic/parser/AddCommandParser.java
> +        Note note = new Note("");
Should this use `ParserUtil.parseNote` instead? Unless if you haven't implemented it yet?

2023-10-16 16:42 UTC, tim-pipi commented on src/main/java/seedu/letsgethired/model/util/SampleDataUtil.java
For the Sample Data, I think it's better to specify it individually instead!

2023-10-16 16:42 UTC, tim-pipi commented on src/main/java/seedu/letsgethired/storage/JsonAdaptedInternApplication.java
> +        final Note modelNote = new Note("");
I think there should be a `@JsonProperty("note")` in the constructor of this file? And also a `note` field as well?

Perhaps we could also try to follow the other fields to specify this, for example:
```suggestion
        if (note == null) {
            throw new IllegalValueException(String.format(MISSING_FIELD_MESSAGE_FORMAT, Note.class.getSimpleName()));
        }
        if (!Note.isValidNote(note)) {
            throw new IllegalValueException(Note.MESSAGE_CONSTRAINTS);
        }
        final Note modelNote = new Note(note);
```

2023-10-16 16:42 UTC, tim-pipi commented on src/test/java/seedu/letsgethired/logic/parser/InternTrackerParserTest.java
> +import seedu.letsgethired.logic.commands.*;
Import statement issue here too! Saw this in a few other places as well! Perhaps we could try using the IntelliJ Checkstyle Plugin to catch these!

2023-10-16 16:59 UTC, AprupKale commented on src/main/java/seedu/letsgethired/logic/parser/InternTrackerParser.java
> +            return new NoteCommandParser().parse(arguments);
The Note command has arguments, hence the parse(arguments); similar to Edit, View and Delete

2023-10-16 17:01 UTC, AprupKale commented
@tim-pipi Will make the required changes. As for the check style, will make fixes after adding all the functionality as the last step for the PR! Thanks.

2023-10-17 18:01 UTC, AprupKale commented
Need to:
- [] Make Note optional for AddCommand
- [] Add test cases for more coverage for appropriate functions

2023-10-18 07:32 UTC, merged