Fix issues with note
AY2324S1-CS2103T-W17-2/tp pull request #59
Opened 2023-10-18 08:03 UTC by AprupKale

Fix all issues found with note inlcuding:
- [ ] Note not being updated in the model
- [ ] Note command without note parameter error

2023-10-18 08:16 UTC, AprupKale commented
@tim-pipi thanks for catching the bugs. I have made the fixes!

2023-10-18 08:22 UTC, tim-pipi requested changes
LGTM overall! Thanks for the changes, could you add the test cases as well to pass the codecov? Thank you for the hard work Aprup!

2023-10-18 08:22 UTC, tim-pipi commented on src/main/java/seedu/letsgethired/logic/commands/NoteCommand.java
```
private String generateSuccessMessage(InternApplication personToEdit) {
        String message = !note.value.isEmpty() ? MESSAGE_ADD_NOTE_SUCCESS : MESSAGE_DELETE_NOTE_SUCCESS;
        return String.format(message, Messages.format(personToEdit));
    }
```
Perhaps this is better to follow the convention of success message of other commands as well!

2023-10-19 08:01 UTC, tim-pipi approved these changes

2023-10-19 08:01 UTC, tim-pipi commented
LGTM! Thanks for the changes! Will merge this PR! 👍

2023-10-19 08:02 UTC, merged